lesson_6_Turcu_Alexandru.py
mariuspodean/CJ-PYTHON-01 pull request #11
Opened 2020-03-31 13:45 UTC by Alexandru-Turcu

2020-03-31 16:00 UTC, Liitle commented
Salut, adaugi te rog fisierele tale intr-un folder 😄 o sa fie mai usor de inteles dupa ce facem merge la toate temele

2020-03-31 17:22 UTC, Liitle reviewed
Overall solid effort. Good Job 👍

2020-03-31 17:22 UTC, Liitle commented on target_practice_9.py
> +            new_object = {'year': years[i], 'coverage': cvg}
this is a nice way of getting the year. Congrats on using `enumerate`

2020-03-31 17:22 UTC, Liitle commented on target_practice_9.py
> +        for i, cvg in enumerate(elem[1]):
`i` and `cvg` can be `index` and `coverage`. The full words are not so long and add a lot of clarity

2020-03-31 17:22 UTC, Liitle commented on target_practice_9.py
> +            if int(entry['year']) == given_year:
It is not necessary to convert to int since we are not doing any operations to the year. `given_year` can be a string when we call the function. If we call the function with a string the int transformation is not required

2020-03-31 17:22 UTC, Liitle commented on target_practice_9.py
> +    to_return = []
a better name for `to_return` will be `year_data`

2020-03-31 17:22 UTC, Liitle commented on target_practice_9.py
> +print('------------------------')
this print statement can be placed at the end since the function code will be run just when we call the functions

2020-03-31 17:22 UTC, Liitle commented on target_practice_9.py
> +print('------------------------')
same as above

2020-03-31 17:22 UTC, Liitle commented on target_practice_9.py
> +print('------------------------')
same as above

2020-03-31 17:22 UTC, Liitle commented on target_practice_9.py
> +            if entry["coverage"][-1] == "b":
you can use strip('b'). If 'b' is not in string `strip` will do nothing

2020-03-31 20:08 UTC, Alexandru-Turcu commented
Salut George,

Am incercat sa pun prima oara intr-un fisier dar nu imi mai
gasea file-ul..apoi am incercat fara folder si a mers.

Putin ajutor in privinta asta si desigur ca il pun intr-un folder :D !

Regards,
Alex

On Tue, Mar 31, 2020 at 7:00 PM George Andrei Dragan <
notifications@github.com> wrote:

> Salut, adaugi te rog fisierele tale intr-un folder 😄 o sa fie mai usor
> de inteles dupa ce facem merge la toate temele
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mariuspodean/CJ-PYTHON-01/pull/11#issuecomment-606719307>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO75S7W45KSMEEKUWJURY2LRKIHRDANCNFSM4LXR77FA>
> .
>

2020-04-04 16:23 UTC, mariuspodean requested changes
merge the files and leave only the final version of the code

2020-04-04 16:31 UTC, merged