Homework lesson 13 class inheritance
mariuspodean/CJ-PYTHON-01 pull request #132
Opened 2020-04-28 21:28 UTC by sorinmosut

2020-04-29 14:42 UTC, vlad-o-git reviewed
From what I understood and based on your code, it seems the PerimeterMixin is a base class of Polygons. So Polygons is a child of PerimeterMixin which I don't think this was Marius plan. The __mro__ should display the mixin class between Triangle and Polygons

2020-04-29 15:23 UTC, sorinmosut commented
I done it like this becouse we will can use the perimeter method for any geometric figure defined by a class. The only restriction in calling the mixin class is that those sould be call first in this case like this :  Polygons(PerimeterMixin, object), but the object is implicitly. So the __init__ is in Polygons and in mixin is only one method.
[<class '__main__.Polygons'>, <class '__main__.PerimeterMixin'>, <class 'object'>]

2020-05-06 16:30 UTC, Liitle requested changes

2020-05-06 16:30 UTC, Liitle commented on lesson_13/mosut_sorin/hw_lesson13_inheritance_mosut_sorin.py
> +class Polygons(PerimeterMixin):
The requirement of the challenge was to have the perimeter method available only for triangle class. If we use it like this we will have perimeter method on all the shapes that use Polygons as a parent

2020-05-06 16:30 UTC, Liitle commented on lesson_13/mosut_sorin/hw_lesson13_inheritance_mosut_sorin.py
> +    def area(self):
This method is supposed to return a new Square object. The logic of getting the sides is correct, but with the sides, we need to create a new object. In order to create a new object we need the class object (cls).

What we can use from python to achieve this?

2020-05-13 15:34 UTC, Liitle approved these changes

2020-05-13 15:34 UTC, merged