Class homework no.9
mariuspodean/CJ-PYTHON-01 pull request #68
Opened 2020-04-10 19:54 UTC by fm1hai

2020-04-10 19:57 UTC, fm1hai commented
homework for lesson 9- class

2020-04-12 09:22 UTC, vlad-o-git commented
Good job!
The second class shouldn't have a second method as initially requested ("at least 2 methods each")?

2020-04-15 17:13 UTC, Liitle requested changes
Nice job for updating the code after the first review! 

God work with the code. Just some code formatting for strings is a bit off, but good job!

2020-04-15 17:13 UTC, Liitle commented on lesson_9/classes_homework_9.py
> +        return f"Due to the size, {self.size} inch, {self.brand} {self.type} is recomandated " \
try to use `""" """` for multiline strings instead of `\`

2020-04-18 14:18 UTC, mariuspodean approved these changes

2020-04-18 14:18 UTC, merged