Please add my lesson 9 homework
mariuspodean/CJ-PYTHON-01 pull request #75
Opened 2020-04-12 08:45 UTC by zoldirazvan

2020-04-15 16:03 UTC, Liitle commented
Hi, you committed the changes on branch lesson_9 and made the pull request from lesson_9 to master.

Please switch to a new branch `lesson_9_razvan_zoldi` and open a new pull request from the new branch to `lesson_9` 

Let me know when you moved the code and I will clean-up the `lesson_9` branch

2020-04-15 17:47 UTC, Liitle reviewed
Nice work.

2020-04-15 17:47 UTC, Liitle commented on lesson_9/lesson_9_zoldi_razvan/lesson_9_zoldi_razvan.py
> +        if int(self.area) == int(ref_country[3]):
You can avoid the int conversion if you initialize the instances directly with int values

2020-04-16 12:30 UTC, zoldirazvan commented
> Hi, you committed the changes on branch lesson_9 and made the pull request from lesson_9 to master.
> 
> Please switch to a new branch `lesson_9_razvan_zoldi` and open a new pull request from the new branch to `lesson_9`. After you move the code you can close this pullrequest
> 
> Let me know when you moved the code and I will clean-up the `lesson_9` branch

Hi, 
In my branch appear two other folders as you can see on attachment. So is possible to commit 2 other's code. I don't understand. 
![image](https://user-images.githubusercontent.com/62897785/79456322-f528de00-7ff6-11ea-931d-c9e745a921fe.png)

2020-04-27 16:09 UTC, mariuspodean requested changes
Please clean the commit so that it includes only the added files (you are also deleting some other files)

2020-04-27 17:12 UTC, zoldirazvan commented
> Please clean the commit so that it includes only the added files (you are also deleting some other files)

I'm not sure how to do that, that is why I'm hesitating. Maybe is wise to delete commit and make another one.

2020-04-27 17:54 UTC, mariuspodean commented
> > Please clean the commit so that it includes only the added files (you are also deleting some other files)
> 
> I'm not sure how to do that, that is why I'm hesitating. Maybe is wise to delete the commit and make another one.

True, here probably it would be easier to make a new branch and add only the new file

2020-04-27 18:34 UTC, closed without merging