Lesson 9 edmond sabou
mariuspodean/CJ-PYTHON-01 pull request #90
Opened 2020-04-15 17:54 UTC by edisabou

2020-04-15 17:56 UTC, Liitle commented
Can you please remove the old lessons for this branch. You will still have the code on the other branches

2020-04-15 18:02 UTC, Liitle reviewed
Nice work.

2020-04-15 19:18 UTC, VictorPop84 requested changes
please commit into lesson_9 not into master

2020-04-18 14:17 UTC, mariuspodean approved these changes

2020-04-18 14:17 UTC, merged